[package]
name = "nafm-agent"
version = "0.3.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "nafm-agent"
path = "src/main.rs"

[dependencies]
nafm-protocol = { path = "../nafm-protocol" }
blake3.workspace = true
serde_json.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true
